/*
 * This file is generated by jOOQ.
 */
package com.mick.vuetinaut.jooq.model.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;
import java.util.UUID;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NotepadUserShare implements Serializable {

    private static final long serialVersionUID = 254038549;

    private UUID      uuid;
    private UUID      notepadUuid;
    private UUID      userUuid;
    private Timestamp dateCreated;

    public NotepadUserShare() {}

    public NotepadUserShare(NotepadUserShare value) {
        this.uuid = value.uuid;
        this.notepadUuid = value.notepadUuid;
        this.userUuid = value.userUuid;
        this.dateCreated = value.dateCreated;
    }

    public NotepadUserShare(
        UUID      uuid,
        UUID      notepadUuid,
        UUID      userUuid,
        Timestamp dateCreated
    ) {
        this.uuid = uuid;
        this.notepadUuid = notepadUuid;
        this.userUuid = userUuid;
        this.dateCreated = dateCreated;
    }

    public UUID getUuid() {
        return this.uuid;
    }

    public void setUuid(UUID uuid) {
        this.uuid = uuid;
    }

    public UUID getNotepadUuid() {
        return this.notepadUuid;
    }

    public void setNotepadUuid(UUID notepadUuid) {
        this.notepadUuid = notepadUuid;
    }

    public UUID getUserUuid() {
        return this.userUuid;
    }

    public void setUserUuid(UUID userUuid) {
        this.userUuid = userUuid;
    }

    public Timestamp getDateCreated() {
        return this.dateCreated;
    }

    public void setDateCreated(Timestamp dateCreated) {
        this.dateCreated = dateCreated;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final NotepadUserShare other = (NotepadUserShare) obj;
        if (uuid == null) {
            if (other.uuid != null)
                return false;
        }
        else if (!uuid.equals(other.uuid))
            return false;
        if (notepadUuid == null) {
            if (other.notepadUuid != null)
                return false;
        }
        else if (!notepadUuid.equals(other.notepadUuid))
            return false;
        if (userUuid == null) {
            if (other.userUuid != null)
                return false;
        }
        else if (!userUuid.equals(other.userUuid))
            return false;
        if (dateCreated == null) {
            if (other.dateCreated != null)
                return false;
        }
        else if (!dateCreated.equals(other.dateCreated))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.uuid == null) ? 0 : this.uuid.hashCode());
        result = prime * result + ((this.notepadUuid == null) ? 0 : this.notepadUuid.hashCode());
        result = prime * result + ((this.userUuid == null) ? 0 : this.userUuid.hashCode());
        result = prime * result + ((this.dateCreated == null) ? 0 : this.dateCreated.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("NotepadUserShare (");

        sb.append(uuid);
        sb.append(", ").append(notepadUuid);
        sb.append(", ").append(userUuid);
        sb.append(", ").append(dateCreated);

        sb.append(")");
        return sb.toString();
    }
}
