/*
 * This file is generated by jOOQ.
 */
package com.mick.vuetinaut.jooq.model.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;
import java.util.UUID;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Note implements Serializable {

    private static final long serialVersionUID = 132634733;

    private UUID      uuid;
    private UUID      notepadUuid;
    private String    body;
    private UUID      creatorUserUuid;
    private UUID      editorUserUuid;
    private Timestamp dateEdited;
    private Timestamp dateCreated;

    public Note() {}

    public Note(Note value) {
        this.uuid = value.uuid;
        this.notepadUuid = value.notepadUuid;
        this.body = value.body;
        this.creatorUserUuid = value.creatorUserUuid;
        this.editorUserUuid = value.editorUserUuid;
        this.dateEdited = value.dateEdited;
        this.dateCreated = value.dateCreated;
    }

    public Note(
        UUID      uuid,
        UUID      notepadUuid,
        String    body,
        UUID      creatorUserUuid,
        UUID      editorUserUuid,
        Timestamp dateEdited,
        Timestamp dateCreated
    ) {
        this.uuid = uuid;
        this.notepadUuid = notepadUuid;
        this.body = body;
        this.creatorUserUuid = creatorUserUuid;
        this.editorUserUuid = editorUserUuid;
        this.dateEdited = dateEdited;
        this.dateCreated = dateCreated;
    }

    public UUID getUuid() {
        return this.uuid;
    }

    public void setUuid(UUID uuid) {
        this.uuid = uuid;
    }

    public UUID getNotepadUuid() {
        return this.notepadUuid;
    }

    public void setNotepadUuid(UUID notepadUuid) {
        this.notepadUuid = notepadUuid;
    }

    public String getBody() {
        return this.body;
    }

    public void setBody(String body) {
        this.body = body;
    }

    public UUID getCreatorUserUuid() {
        return this.creatorUserUuid;
    }

    public void setCreatorUserUuid(UUID creatorUserUuid) {
        this.creatorUserUuid = creatorUserUuid;
    }

    public UUID getEditorUserUuid() {
        return this.editorUserUuid;
    }

    public void setEditorUserUuid(UUID editorUserUuid) {
        this.editorUserUuid = editorUserUuid;
    }

    public Timestamp getDateEdited() {
        return this.dateEdited;
    }

    public void setDateEdited(Timestamp dateEdited) {
        this.dateEdited = dateEdited;
    }

    public Timestamp getDateCreated() {
        return this.dateCreated;
    }

    public void setDateCreated(Timestamp dateCreated) {
        this.dateCreated = dateCreated;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Note other = (Note) obj;
        if (uuid == null) {
            if (other.uuid != null)
                return false;
        }
        else if (!uuid.equals(other.uuid))
            return false;
        if (notepadUuid == null) {
            if (other.notepadUuid != null)
                return false;
        }
        else if (!notepadUuid.equals(other.notepadUuid))
            return false;
        if (body == null) {
            if (other.body != null)
                return false;
        }
        else if (!body.equals(other.body))
            return false;
        if (creatorUserUuid == null) {
            if (other.creatorUserUuid != null)
                return false;
        }
        else if (!creatorUserUuid.equals(other.creatorUserUuid))
            return false;
        if (editorUserUuid == null) {
            if (other.editorUserUuid != null)
                return false;
        }
        else if (!editorUserUuid.equals(other.editorUserUuid))
            return false;
        if (dateEdited == null) {
            if (other.dateEdited != null)
                return false;
        }
        else if (!dateEdited.equals(other.dateEdited))
            return false;
        if (dateCreated == null) {
            if (other.dateCreated != null)
                return false;
        }
        else if (!dateCreated.equals(other.dateCreated))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.uuid == null) ? 0 : this.uuid.hashCode());
        result = prime * result + ((this.notepadUuid == null) ? 0 : this.notepadUuid.hashCode());
        result = prime * result + ((this.body == null) ? 0 : this.body.hashCode());
        result = prime * result + ((this.creatorUserUuid == null) ? 0 : this.creatorUserUuid.hashCode());
        result = prime * result + ((this.editorUserUuid == null) ? 0 : this.editorUserUuid.hashCode());
        result = prime * result + ((this.dateEdited == null) ? 0 : this.dateEdited.hashCode());
        result = prime * result + ((this.dateCreated == null) ? 0 : this.dateCreated.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Note (");

        sb.append(uuid);
        sb.append(", ").append(notepadUuid);
        sb.append(", ").append(body);
        sb.append(", ").append(creatorUserUuid);
        sb.append(", ").append(editorUserUuid);
        sb.append(", ").append(dateEdited);
        sb.append(", ").append(dateCreated);

        sb.append(")");
        return sb.toString();
    }
}
