/*
 * This file is generated by jOOQ.
 */
package com.mick.vuetinaut.jooq.model;


import com.mick.vuetinaut.jooq.model.tables.Notepad;
import com.mick.vuetinaut.jooq.model.tables.NotepadUserShare;
import com.mick.vuetinaut.jooq.model.tables.User;
import com.mick.vuetinaut.jooq.model.tables.records.NotepadRecord;
import com.mick.vuetinaut.jooq.model.tables.records.NotepadUserShareRecord;
import com.mick.vuetinaut.jooq.model.tables.records.UserRecord;

import javax.annotation.Generated;

import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<NotepadRecord> NOTEPAD_PKEY = UniqueKeys0.NOTEPAD_PKEY;
    public static final UniqueKey<NotepadUserShareRecord> NOTEPAD_USER_SHARE_PKEY = UniqueKeys0.NOTEPAD_USER_SHARE_PKEY;
    public static final UniqueKey<UserRecord> USER_PKEY = UniqueKeys0.USER_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<NotepadRecord> NOTEPAD_PKEY = Internal.createUniqueKey(Notepad.NOTEPAD, "notepad_pkey", Notepad.NOTEPAD.UUID);
        public static final UniqueKey<NotepadUserShareRecord> NOTEPAD_USER_SHARE_PKEY = Internal.createUniqueKey(NotepadUserShare.NOTEPAD_USER_SHARE, "notepad_user_share_pkey", NotepadUserShare.NOTEPAD_USER_SHARE.UUID);
        public static final UniqueKey<UserRecord> USER_PKEY = Internal.createUniqueKey(User.USER, "user_pkey", User.USER.UUID);
    }
}
