/*
 * This file is generated by jOOQ.
 */
package com.mick.vuetinaut.jooq.model;


import com.mick.vuetinaut.jooq.model.tables.Notepad;
import com.mick.vuetinaut.jooq.model.tables.NotepadUserShare;
import com.mick.vuetinaut.jooq.model.tables.User;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.notepad</code>.
     */
    public static final Notepad NOTEPAD = com.mick.vuetinaut.jooq.model.tables.Notepad.NOTEPAD;

    /**
     * The table <code>public.notepad_user_share</code>.
     */
    public static final NotepadUserShare NOTEPAD_USER_SHARE = com.mick.vuetinaut.jooq.model.tables.NotepadUserShare.NOTEPAD_USER_SHARE;

    /**
     * The table <code>public.user</code>.
     */
    public static final User USER = com.mick.vuetinaut.jooq.model.tables.User.USER;
}
