micronaut:
  application:
    name: vuetinaut
  server:
    port: ${PORT:8081}
    cors:
      enabled: ${ENABLE_CORS:true}
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /api-docs/**
  security:
    enabled: true
    endpoints:
      login:
        enabled: true
    token:
      jwt:
        enabled: true
        bearer:
          enabled: false
        cookie:
          enabled: true
          loginFailureTargetUrl: http://localhost:8080/#/login
          loginSuccessTargetUrl: http://localhost:8080/#/home
        signatures:
          secret:
            generator:
              secret: yourmomyourmomyourmomyourmomyourmomyourmomyourmomyourmom

db:
  url: ${DATABASE_URL:`postgresql://postgres:postgres@localhost:5432/postgres`}
  min-pool: 2
  max-pool: 5
  connection-timeout: 20000