micronaut:
  application:
    name: vuetinaut
  server:
    port: ${PORT:8081}
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /api-docs/**
      default:
        enabled: true
        mapping: "/**"
        paths: "file:/opt/ui/dist"
  security:
    enabled: true

    intercept-url-map:
      - pattern: /**
        access:
          - isAnonymous()
      - pattern: /api/**
        access:
          - isAuthenticated()
    endpoints:
      login:
        enabled: true
        path: /api/login
      logout:
        enabled: true
        path: /api/logout

    token:
      jwt:
        generator:
          access-token-expiration: 31536000000 #large number
        enabled: true
        bearer:
          enabled: false
        cookie:
          redirect:
            enabled: false
          enabled: true
          loginFailureTargetUrl: /#/login
          loginSuccessTargetUrl: /#/
        signatures:
          secret:
            generator:
              secret: yourmomyourmomyourmomyourmomyourmomyourmomyourmomyourmom

password:
  salt: somecoolsalt

db:
  url: ${DATABASE_URL:`postgresql://postgres:postgres@localhost:5432/postgres`}
  min-pool: 2
  max-pool: 5
  connection-timeout: 20000