/*
 * This file is generated by jOOQ.
 */
package com.mick.vuetinaut.jooq.model.tables.daos;


import com.mick.vuetinaut.jooq.model.tables.Notepad;
import com.mick.vuetinaut.jooq.model.tables.records.NotepadRecord;

import java.sql.Timestamp;
import java.util.List;
import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NotepadDao extends DAOImpl<NotepadRecord, com.mick.vuetinaut.jooq.model.tables.pojos.Notepad, UUID> {

    /**
     * Create a new NotepadDao without any configuration
     */
    public NotepadDao() {
        super(Notepad.NOTEPAD, com.mick.vuetinaut.jooq.model.tables.pojos.Notepad.class);
    }

    /**
     * Create a new NotepadDao with an attached configuration
     */
    public NotepadDao(Configuration configuration) {
        super(Notepad.NOTEPAD, com.mick.vuetinaut.jooq.model.tables.pojos.Notepad.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected UUID getId(com.mick.vuetinaut.jooq.model.tables.pojos.Notepad object) {
        return object.getUuid();
    }

    /**
     * Fetch records that have <code>uuid IN (values)</code>
     */
    public List<com.mick.vuetinaut.jooq.model.tables.pojos.Notepad> fetchByUuid(UUID... values) {
        return fetch(Notepad.NOTEPAD.UUID, values);
    }

    /**
     * Fetch a unique record that has <code>uuid = value</code>
     */
    public com.mick.vuetinaut.jooq.model.tables.pojos.Notepad fetchOneByUuid(UUID value) {
        return fetchOne(Notepad.NOTEPAD.UUID, value);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.mick.vuetinaut.jooq.model.tables.pojos.Notepad> fetchByName(String... values) {
        return fetch(Notepad.NOTEPAD.NAME, values);
    }

    /**
     * Fetch records that have <code>creator_user_uuid IN (values)</code>
     */
    public List<com.mick.vuetinaut.jooq.model.tables.pojos.Notepad> fetchByCreatorUserUuid(UUID... values) {
        return fetch(Notepad.NOTEPAD.CREATOR_USER_UUID, values);
    }

    /**
     * Fetch records that have <code>date_created IN (values)</code>
     */
    public List<com.mick.vuetinaut.jooq.model.tables.pojos.Notepad> fetchByDateCreated(Timestamp... values) {
        return fetch(Notepad.NOTEPAD.DATE_CREATED, values);
    }
}
