/*
 * This file is generated by jOOQ.
 */
package com.mick.vuetinaut.jooq.model.tables.records;


import com.mick.vuetinaut.jooq.model.tables.Notepad;

import java.sql.Timestamp;
import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NotepadRecord extends UpdatableRecordImpl<NotepadRecord> implements Record7<UUID, String, String, UUID, Timestamp, UUID, Timestamp> {

    private static final long serialVersionUID = -1685011231;

    /**
     * Setter for <code>public.notepad.uuid</code>.
     */
    public void setUuid(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.notepad.uuid</code>.
     */
    public UUID getUuid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.notepad.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.notepad.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.notepad.body</code>.
     */
    public void setBody(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.notepad.body</code>.
     */
    public String getBody() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.notepad.editor_user_uuid</code>.
     */
    public void setEditorUserUuid(UUID value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.notepad.editor_user_uuid</code>.
     */
    public UUID getEditorUserUuid() {
        return (UUID) get(3);
    }

    /**
     * Setter for <code>public.notepad.date_edited</code>.
     */
    public void setDateEdited(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.notepad.date_edited</code>.
     */
    public Timestamp getDateEdited() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>public.notepad.creator_user_uuid</code>.
     */
    public void setCreatorUserUuid(UUID value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.notepad.creator_user_uuid</code>.
     */
    public UUID getCreatorUserUuid() {
        return (UUID) get(5);
    }

    /**
     * Setter for <code>public.notepad.date_created</code>.
     */
    public void setDateCreated(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.notepad.date_created</code>.
     */
    public Timestamp getDateCreated() {
        return (Timestamp) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<UUID, String, String, UUID, Timestamp, UUID, Timestamp> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<UUID, String, String, UUID, Timestamp, UUID, Timestamp> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field1() {
        return Notepad.NOTEPAD.UUID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Notepad.NOTEPAD.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Notepad.NOTEPAD.BODY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field4() {
        return Notepad.NOTEPAD.EDITOR_USER_UUID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return Notepad.NOTEPAD.DATE_EDITED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field6() {
        return Notepad.NOTEPAD.CREATOR_USER_UUID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return Notepad.NOTEPAD.DATE_CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID component1() {
        return getUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getBody();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID component4() {
        return getEditorUserUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getDateEdited();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID component6() {
        return getCreatorUserUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getDateCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value1() {
        return getUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getBody();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value4() {
        return getEditorUserUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getDateEdited();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value6() {
        return getCreatorUserUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getDateCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NotepadRecord value1(UUID value) {
        setUuid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NotepadRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NotepadRecord value3(String value) {
        setBody(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NotepadRecord value4(UUID value) {
        setEditorUserUuid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NotepadRecord value5(Timestamp value) {
        setDateEdited(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NotepadRecord value6(UUID value) {
        setCreatorUserUuid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NotepadRecord value7(Timestamp value) {
        setDateCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NotepadRecord values(UUID value1, String value2, String value3, UUID value4, Timestamp value5, UUID value6, Timestamp value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NotepadRecord
     */
    public NotepadRecord() {
        super(Notepad.NOTEPAD);
    }

    /**
     * Create a detached, initialised NotepadRecord
     */
    public NotepadRecord(UUID uuid, String name, String body, UUID editorUserUuid, Timestamp dateEdited, UUID creatorUserUuid, Timestamp dateCreated) {
        super(Notepad.NOTEPAD);

        set(0, uuid);
        set(1, name);
        set(2, body);
        set(3, editorUserUuid);
        set(4, dateEdited);
        set(5, creatorUserUuid);
        set(6, dateCreated);
    }
}
