/*
 * This file is generated by jOOQ.
 */
package com.mick.vuetinaut.jooq.model.tables.records;


import com.mick.vuetinaut.jooq.model.tables.Note;

import java.sql.Timestamp;
import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NoteRecord extends UpdatableRecordImpl<NoteRecord> implements Record7<UUID, UUID, String, UUID, UUID, Timestamp, Timestamp> {

    private static final long serialVersionUID = -734886249;

    /**
     * Setter for <code>public.note.uuid</code>.
     */
    public void setUuid(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.note.uuid</code>.
     */
    public UUID getUuid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.note.notepad_uuid</code>.
     */
    public void setNotepadUuid(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.note.notepad_uuid</code>.
     */
    public UUID getNotepadUuid() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.note.body</code>.
     */
    public void setBody(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.note.body</code>.
     */
    public String getBody() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.note.creator_user_uuid</code>.
     */
    public void setCreatorUserUuid(UUID value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.note.creator_user_uuid</code>.
     */
    public UUID getCreatorUserUuid() {
        return (UUID) get(3);
    }

    /**
     * Setter for <code>public.note.editor_user_uuid</code>.
     */
    public void setEditorUserUuid(UUID value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.note.editor_user_uuid</code>.
     */
    public UUID getEditorUserUuid() {
        return (UUID) get(4);
    }

    /**
     * Setter for <code>public.note.date_edited</code>.
     */
    public void setDateEdited(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.note.date_edited</code>.
     */
    public Timestamp getDateEdited() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>public.note.date_created</code>.
     */
    public void setDateCreated(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.note.date_created</code>.
     */
    public Timestamp getDateCreated() {
        return (Timestamp) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<UUID, UUID, String, UUID, UUID, Timestamp, Timestamp> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<UUID, UUID, String, UUID, UUID, Timestamp, Timestamp> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field1() {
        return Note.NOTE.UUID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field2() {
        return Note.NOTE.NOTEPAD_UUID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Note.NOTE.BODY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field4() {
        return Note.NOTE.CREATOR_USER_UUID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field5() {
        return Note.NOTE.EDITOR_USER_UUID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return Note.NOTE.DATE_EDITED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return Note.NOTE.DATE_CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID component1() {
        return getUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID component2() {
        return getNotepadUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getBody();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID component4() {
        return getCreatorUserUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID component5() {
        return getEditorUserUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getDateEdited();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getDateCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value1() {
        return getUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value2() {
        return getNotepadUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getBody();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value4() {
        return getCreatorUserUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value5() {
        return getEditorUserUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getDateEdited();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getDateCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NoteRecord value1(UUID value) {
        setUuid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NoteRecord value2(UUID value) {
        setNotepadUuid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NoteRecord value3(String value) {
        setBody(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NoteRecord value4(UUID value) {
        setCreatorUserUuid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NoteRecord value5(UUID value) {
        setEditorUserUuid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NoteRecord value6(Timestamp value) {
        setDateEdited(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NoteRecord value7(Timestamp value) {
        setDateCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NoteRecord values(UUID value1, UUID value2, String value3, UUID value4, UUID value5, Timestamp value6, Timestamp value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NoteRecord
     */
    public NoteRecord() {
        super(Note.NOTE);
    }

    /**
     * Create a detached, initialised NoteRecord
     */
    public NoteRecord(UUID uuid, UUID notepadUuid, String body, UUID creatorUserUuid, UUID editorUserUuid, Timestamp dateEdited, Timestamp dateCreated) {
        super(Note.NOTE);

        set(0, uuid);
        set(1, notepadUuid);
        set(2, body);
        set(3, creatorUserUuid);
        set(4, editorUserUuid);
        set(5, dateEdited);
        set(6, dateCreated);
    }
}
