/*
 * This file is generated by jOOQ.
 */
package com.mick.vuetinaut.jooq.model.tables;


import com.mick.vuetinaut.jooq.model.Indexes;
import com.mick.vuetinaut.jooq.model.Keys;
import com.mick.vuetinaut.jooq.model.Public;
import com.mick.vuetinaut.jooq.model.tables.records.NotepadUserShareRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NotepadUserShare extends TableImpl<NotepadUserShareRecord> {

    private static final long serialVersionUID = 835483304;

    /**
     * The reference instance of <code>public.notepad_user_share</code>
     */
    public static final NotepadUserShare NOTEPAD_USER_SHARE = new NotepadUserShare();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<NotepadUserShareRecord> getRecordType() {
        return NotepadUserShareRecord.class;
    }

    /**
     * The column <code>public.notepad_user_share.uuid</code>.
     */
    public final TableField<NotepadUserShareRecord, UUID> UUID = createField("uuid", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.notepad_user_share.notepad_uuid</code>.
     */
    public final TableField<NotepadUserShareRecord, UUID> NOTEPAD_UUID = createField("notepad_uuid", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.notepad_user_share.user_uuid</code>.
     */
    public final TableField<NotepadUserShareRecord, UUID> USER_UUID = createField("user_uuid", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.notepad_user_share.date_created</code>.
     */
    public final TableField<NotepadUserShareRecord, Timestamp> DATE_CREATED = createField("date_created", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * Create a <code>public.notepad_user_share</code> table reference
     */
    public NotepadUserShare() {
        this(DSL.name("notepad_user_share"), null);
    }

    /**
     * Create an aliased <code>public.notepad_user_share</code> table reference
     */
    public NotepadUserShare(String alias) {
        this(DSL.name(alias), NOTEPAD_USER_SHARE);
    }

    /**
     * Create an aliased <code>public.notepad_user_share</code> table reference
     */
    public NotepadUserShare(Name alias) {
        this(alias, NOTEPAD_USER_SHARE);
    }

    private NotepadUserShare(Name alias, Table<NotepadUserShareRecord> aliased) {
        this(alias, aliased, null);
    }

    private NotepadUserShare(Name alias, Table<NotepadUserShareRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> NotepadUserShare(Table<O> child, ForeignKey<O, NotepadUserShareRecord> key) {
        super(child, key, NOTEPAD_USER_SHARE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.NOTEPAD_USER_SHARE_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<NotepadUserShareRecord> getPrimaryKey() {
        return Keys.NOTEPAD_USER_SHARE_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<NotepadUserShareRecord>> getKeys() {
        return Arrays.<UniqueKey<NotepadUserShareRecord>>asList(Keys.NOTEPAD_USER_SHARE_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NotepadUserShare as(String alias) {
        return new NotepadUserShare(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NotepadUserShare as(Name alias) {
        return new NotepadUserShare(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public NotepadUserShare rename(String name) {
        return new NotepadUserShare(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public NotepadUserShare rename(Name name) {
        return new NotepadUserShare(name, null);
    }
}
