name: Build and publish

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: Setup node
      uses: actions/setup-node@v1.1.0
    
    - name: run ui build
      run: cd ui && npm install && npm run build
    
    - name: GitHub Action for Heroku
      uses: actions/heroku@1.0.0
      
    - name: login
      uses: actions/heroku@master
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      with:
        args: container:login
    - name: push
      uses: actions/heroku@master
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      with:
        args: container:push -a micknotes web
    - name: release
      uses: actions/heroku@master
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      with:
        args: container:release -a micknotes web
     

    
    
